version: '3.8'
services:
    blog:
        image: node:16
        command: sh -c "yarn install && yarn dev"
        environment: 
            NODE_ENV: development
        volumes: 
            - './docs:/app'
        working_dir: /app
        stdin_open: true
        ports: 
            - '8080:8080'
